version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: dulwich
    versions:
    - 0.20.15
    - 0.20.18
    - 0.20.19
    - 0.20.20
  - dependency-name: markdown
    versions:
    - 3.3.3
